[package]
name = "castscreen-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
windows.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
eframe = { workspace = true }
egui_extras = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
approx = "0.5"
